src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OfferRepository::class)]
class Offer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $housing_type = null;

    #[ORM\Column(length: 255)]
    private ?string $department = null;

    #[ORM\Column(length: 255)]
    private ?string $postcode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\OneToMany(mappedBy: 'offer', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\ManyToOne(inversedBy: 'offers')]
    private ?User $farmerId = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $animals = null;

    #[ORM\Column]
    private ?int $superficie = null;

    #[ORM\Column(length: 255)]
    private ?string $activity = null;

    public function __construct()
    {
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHousingType(): ?string
    {
        return $this->housing_type;
    }

    public function setHousingType(string $housing_type): self
    {
        $this->housing_type = $housing_type;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(string $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setOffer($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getOffer() === $this) {
                $booking->setOffer(null);
            }
        }

        return $this;
    }

    public function getFarmerId(): ?User
    {
        return $this->farmerId;
    }

    public function setFarmerId(?User $farmerId): self
    {
        $this->farmerId = $farmerId;

        return $this;
    }

    public function getAnimals(): ?string
    {
        return $this->animals;
    }

    public function setAnimals(?string $animals): self
    {
        $this->animals = $animals;

        return $this;
    }

    public function getSuperficie(): ?int
    {
        return $this->superficie;
    }

    public function setSuperficie(int $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getActivity(): ?string
    {
        return $this->activity;
    }

    public function setActivity(string $activity): self
    {
        $this->activity = $activity;

        return $this;
    }
}

src/Form/OfferType.php
<?php

namespace App\Form;

use App\Entity\Offer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OfferType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('housing_type')
            ->add('department')
            ->add('postcode')
            ->add('city')
            ->add('picture')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offer::class,
        ]);
    }
}

src/Controller/OfferController.php
<?php

namespace App\Controller;

use App\Entity\Offer;
use App\Form\OfferType;
use App\Repository\OfferRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/offer')]
class OfferController extends AbstractController
{
    #[Route('/', name: 'app_offer_index', methods: ['GET'])]
    public function index(OfferRepository $offerRepository): Response
    {
        return $this->render('offer/index.html.twig', [
            'offers' => $offerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_offer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OfferRepository $offerRepository): Response
    {
        $offer = new Offer();
        $form = $this->createForm(OfferType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offerRepository->save($offer, true);

            return $this->redirectToRoute('app_offer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offer/new.html.twig', [
            'offer' => $offer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offer_show', methods: ['GET'])]
    public function show(Offer $offer): Response
    {
        return $this->render('offer/show.html.twig', [
            'offer' => $offer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_offer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Offer $offer, OfferRepository $offerRepository): Response
    {
        $form = $this->createForm(OfferType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offerRepository->save($offer, true);

            return $this->redirectToRoute('app_offer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('offer/edit.html.twig', [
            'offer' => $offer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_offer_delete', methods: ['POST'])]
    public function delete(Request $request, Offer $offer, OfferRepository $offerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offer->getId(), $request->request->get('_token'))) {
            $offerRepository->remove($offer, true);
        }

        return $this->redirectToRoute('app_offer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/offer/_delete_form.html.twig
<form method="post" action="{{ path('app_offer_delete', {'id': offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/offer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Offer{% endblock %}

{% block body %}
    <h1>Edit Offer</h1>

    {{ include('offer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_offer_index') }}">back to list</a>

    {{ include('offer/_delete_form.html.twig') }}
{% endblock %}

templates/offer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offer index{% endblock %}

{% block body %}
  <div class="container"> 
    <h3>Rejoignez une exploitation</h3>

    <p>Choisissez une exploitation où effectuer votre séjour ! En échange d’un travail, vous êtes nourris et loger par l’agriculteur. Profiter du milieu agricole tout en apprenant ! </p>

    <div class="row">
        {% for offer in offers %}

          <div class="col-md-4">
            <div class="card" style="height:460px; margin-bottom: 15px">
              <div style="position: absolute; top: 10px; right: 10px;"><span class="badge text-bg-warning">{{ offer.activity }}</span></div>
              <img src="{{ offer.picture }}" class="card-img-top img-fluid" alt="..."  style="height:260px;">
              <div class="card-body">
                  <h5 class="card-title">{{ offer.title }}</h5>
                  <p class="card-text">{{ offer.description }}</p>
                  <p class="card-text"><small class="text-muted">{{ offer.city }} - {{ offer.department }}</small></p>
                  <a href="{{ path('app_offer_show', {'id': offer.id}) }}" class="btn btn-success btn-sm">plus d'info</a>
              </div>
            </div>
          </div>

        {% endfor %}    
  </div>
{% endblock %}


{# 
                    <a href="{{ path('app_offer_edit', {'id': offer.id}) }}">edit</a>

                    <a href="{{ path('app_offer_new') }}">Create new</a> #}

templates/offer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offer{% endblock %}

{% block body %}
    <h1>Create new Offer</h1>

    {{ include('offer/_form.html.twig') }}

    <a href="{{ path('app_offer_index') }}">back to list</a>
{% endblock %}

templates/offer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offer{% endblock %}

{% block body %}
    <h1>Offer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offer.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ offer.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ offer.description }}</td>
            </tr>
            <tr>
                <th>Housing_type</th>
                <td>{{ offer.housingType }}</td>
            </tr>
            <tr>
                <th>Department</th>
                <td>{{ offer.department }}</td>
            </tr>
            <tr>
                <th>Postcode</th>
                <td>{{ offer.postcode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ offer.city }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ offer.picture }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_offer_index') }}">back to list</a>

    <a href="{{ path('app_offer_edit', {'id': offer.id}) }}">edit</a>

    {{ include('offer/_delete_form.html.twig') }}
{% endblock %}